# SVM Support Vector Machine:

## 1.SVC Support Vector Classifier Model (Wine Dataset)

## 2.SVR Support Vector Regression Model (Graduate Admission Dataset)

### Dhravath Ramdas 

dataset and code github link: https://github.com/dharavathramdas101/Machine-learning-Algorithms-Practical-implementation/tree/main/SVM/Red-Wine-Quality%20(%20SVC%20)

## Life Cycle of Machine Learning Project

1.Understanding the Problem Statement
2.Data Collection
3.Exploratory data analysis
4.Data Cleaning
5.Data Pre-Processing
6.Model Training
7.Choose best model

## 1.SVC Support Vector Classifier Model (Wine Dataset)

### Problem Statement

by using SVC to predict  the quality ([5, 6, 7, 4, 8, 3])

### Data Collection

In [ ]:
Dataset link: https://github.com/dharavathramdas101/Machine-learning-Algorithms-Practical-implementation/blob/main/SVM/Red-Wine-Quality%20(%20SVC%20)/winequality-red.csv

### Importing the required packages

In [90]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

### Importing the dataset

In [92]:
data=pd.read_csv("https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/master/winequality-red.csv")

1.import data
2.EDA
3.Preprocessing 
4.model (svm)(svc)
5.evaluation (performance matrix)(confusion matrix)


In [3]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

### Check the unique values in quality

In [4]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [5]:
data.quality

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [6]:
data['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [7]:
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

### dataset information

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


### Describe for stats analysis

In [9]:
data.describe().T

count       mean        std      min      25%  \
fixed acidity         1599.0   8.319637   1.741096  4.60000   7.1000   
volatile acidity      1599.0   0.527821   0.179060  0.12000   0.3900   
citric acid           1599.0   0.270976   0.194801  0.00000   0.0900   
residual sugar        1599.0   2.538806   1.409928  0.90000   1.9000   
chlorides             1599.0   0.087467   0.047065  0.01200   0.0700   
free sulfur dioxide   1599.0  15.874922  10.460157  1.00000   7.0000   
total sulfur dioxide  1599.0  46.467792  32.895324  6.00000  22.0000   
density               1599.0   0.996747   0.001887  0.99007   0.9956   
pH                    1599.0   3.311113   0.154386  2.74000   3.2100   
sulphates             1599.0   0.658149   0.169507  0.33000   0.5500   
alcohol               1599.0  10.422983   1.065668  8.40000   9.5000   
quality               1599.0   5.636023   0.807569  3.00000   5.0000   

                           50%        75%        max  
fixed acidity          7.90000   9.200000   15.90000  
volatile acidity       0.52000   0.640000    1.58000  
citric acid            0.26000   0.420000    1.00000  
residual sugar         2.20000   2.600000   15.50000  
chlorides              0.07900   0.090000    0.61100  
free sulfur dioxide   14.00000  21.000000   72.00000  
total sulfur dioxide  38.00000  62.000000  289.00000  
density                0.99675   0.997835    1.00369  
pH                     3.31000   3.400000    4.01000  
sulphates              0.62000   0.730000    2.00000  
alcohol               10.20000  11.100000   14.90000  
quality                6.00000   6.000000    8.00000

### Independent and Dependent Separation

In [10]:
X = data.drop("quality",axis=1)
X.head(3)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   

   alcohol  
0      9.4  
1      9.8  
2      9.8

In [11]:
y = data['quality']
y.head(3)

0    5
1    5
2    5
Name: quality, dtype: int64

### Train Test Split

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

### Standardsclaer

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
scaler.fit(X_train)##calculate the mean and std dev

StandardScaler()

In [17]:
print(scaler.mean_)

[ 8.30345472  0.53246499  0.26933707  2.54691877  0.08772736 15.91223156
 46.76330532  0.99677933  3.31453782  0.65881419 10.41521942]


In [18]:
X_train_tf = scaler.fit_transform(X_train)

In [19]:
X_test_tf = scaler.transform(X_test)

### SVM

In [21]:
from sklearn.svm import SVC
model = SVC()

In [22]:
model.fit(X_train_tf,y_train)

SVC()

In [23]:
model.score(X_train_tf,y_train)

0.6778711484593838

### Model Prediction

In [24]:
y_predict = model.predict(X_test_tf)
y_predict

array([5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 5, 7, 5, 6, 7, 5, 5, 5,
       6, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5,
       6, 6, 6, 6, 5, 6, 5, 5, 6, 7, 5, 5, 6, 5, 6, 5, 6, 6, 5, 5, 7, 5,
       6, 5, 7, 5, 6, 5, 6, 6, 6, 5, 7, 5, 6, 7, 5, 7, 5, 5, 6, 6, 5, 6,
       6, 5, 6, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 6, 5,
       5, 6, 6, 5, 5, 5, 5, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6,
       6, 6, 5, 6, 5, 6, 7, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 6, 5, 7, 6,
       6, 5, 5, 5, 5, 7, 5, 7, 5, 6, 6, 6, 7, 5, 6, 6, 5, 6, 6, 5, 5, 5,
       6, 6, 5, 5, 5, 5, 7, 6, 5, 5, 6, 6, 7, 5, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 6, 6, 6, 5, 5, 5, 7, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5, 5, 5,
       6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 7,
       6, 7, 6, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 7, 5, 5, 5, 5, 6,
       5, 6, 5, 6, 5, 7, 6, 5, 5, 6, 5, 6, 6, 7, 5,

### Performence Metrics

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, classification_report

### Confusion Matrix

In [26]:
con_mat = confusion_matrix(y_test,y_predict)
con_mat

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,  13,   6,   0,   0],
       [  0,   0, 170,  46,   1,   0],
       [  0,   0,  76, 127,  10,   0],
       [  0,   0,   0,  51,  19,   0],
       [  0,   0,   0,   3,   4,   0]], dtype=int64)

### Accuracy Score

In [27]:
accuracy_score(y_test,y_predict)

0.5984848484848485

### Classification Report

In [28]:
report = classification_report(y_test,y_predict,zero_division=False)
print(report)

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        19
           5       0.65      0.78      0.71       217
           6       0.55      0.60      0.57       213
           7       0.56      0.27      0.37        70
           8       0.00      0.00      0.00         7

    accuracy                           0.60       528
   macro avg       0.29      0.28      0.27       528
weighted avg       0.56      0.60      0.57       528



## Logistic Regression

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
model2 = LogisticRegression()

In [32]:
model2.fit(X_train_tf,y_train)

LogisticRegression()

In [33]:
logis_pred = model2.predict(X_test_tf)

In [34]:
accuracy_score(y_test,logis_pred)

0.571969696969697

In [35]:
logis_report = classification_report(logis_pred,y_test,zero_division = False)
print(logis_report)

              precision    recall  f1-score   support

           3       0.50      0.50      0.50         2
           4       0.05      1.00      0.10         1
           5       0.76      0.64      0.69       258
           6       0.56      0.52      0.54       228
           7       0.24      0.44      0.31        39
           8       0.00      0.00      0.00         0

    accuracy                           0.57       528
   macro avg       0.35      0.52      0.36       528
weighted avg       0.63      0.57      0.60       528



## increase the performance of model

In [37]:
ploy_model = SVC(kernel='poly',C=1.0)
ploy_model.fit(X_train_tf,y_train)
ploy_y_predict = ploy_model.predict(X_test_tf)
accuracy_score(y_test,ploy_y_predict)

0.5587121212121212

In [38]:
list1 = ['poly','linear','sigmoid','rbf']

In [39]:
for i in list1:
    model = SVC(kernel=i,C=1.0)
    model.fit(X_train_tf,y_train)
    y_predict = model.predict(X_test_tf)
    print("kernal {} model accuracy is {}".format(i,accuracy_score(y_test,y_predict)))

kernal poly model accuracy is 0.5587121212121212
kernal linear model accuracy is 0.5587121212121212
kernal sigmoid model accuracy is 0.4734848484848485
kernal rbf model accuracy is 0.5984848484848485


In [40]:
for i in list1:
    model = SVC(kernel=i,C=100.0)
    model.fit(X_train_tf,y_train)
    y_predict = model.predict(X_test_tf)
    print("kernal {} model accuracy is {}".format(i,accuracy_score(y_test,y_predict)))

kernal poly model accuracy is 0.5549242424242424
kernal linear model accuracy is 0.5625
kernal sigmoid model accuracy is 0.42234848484848486
kernal rbf model accuracy is 0.5871212121212122


## Gridsearchcv

In [42]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV

In [43]:
parameters = {"kernel":('linear','rbf','poly','sigmoid'),'C':[1,10]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
model = clf.fit(X_train_tf,y_train)

In [44]:
clf.best_params_

{'C': 10, 'kernel': 'rbf'}

In [45]:
model.score(X_test_tf,y_test)

0.615530303030303

Observation:
    accuracy is increased from 0.58 to 0.61

## 2.SVR Support Vector Regression Model (Graduate Admission Dataset)

### Problem

 problem: predicting the chance of Graduate admission 

In [68]:
df1=pd.read_csv("https://raw.githubusercontent.com/srinivasav22/Graduate-Admission-Prediction/master/Admission_Predict_Ver1.1.csv")

In [69]:
df1.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [70]:
df1.drop("Serial No.",axis=1,inplace=True)

In [71]:
df1.head(3)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72

In [72]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   GRE Score          500 non-null    int64  
 1   TOEFL Score        500 non-null    int64  
 2   University Rating  500 non-null    int64  
 3   SOP                500 non-null    float64
 4   LOR                500 non-null    float64
 5   CGPA               500 non-null    float64
 6   Research           500 non-null    int64  
 7   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 31.4 KB


In [73]:
df1.describe().T

count       mean        std     min       25%     50%  \
GRE Score          500.0  316.47200  11.295148  290.00  308.0000  317.00   
TOEFL Score        500.0  107.19200   6.081868   92.00  103.0000  107.00   
University Rating  500.0    3.11400   1.143512    1.00    2.0000    3.00   
SOP                500.0    3.37400   0.991004    1.00    2.5000    3.50   
LOR                500.0    3.48400   0.925450    1.00    3.0000    3.50   
CGPA               500.0    8.57644   0.604813    6.80    8.1275    8.56   
Research           500.0    0.56000   0.496884    0.00    0.0000    1.00   
Chance of Admit    500.0    0.72174   0.141140    0.34    0.6300    0.72   

                      75%     max  
GRE Score          325.00  340.00  
TOEFL Score        112.00  120.00  
University Rating    4.00    5.00  
SOP                  4.00    5.00  
LOR                  4.00    5.00  
CGPA                 9.04    9.92  
Research             1.00    1.00  
Chance of Admit      0.82    0.97

In [74]:
df1.isnull().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

## Spliting data into independent and dependent features

In [75]:
X1 = df1.iloc[:,:-1]
y1 = df1.iloc[:,-1]

In [76]:
X1.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0        337          118                  4  4.5   4.5  9.65         1
1        324          107                  4  4.0   4.5  8.87         1
2        316          104                  3  3.0   3.5  8.00         1
3        322          110                  3  3.5   2.5  8.67         1
4        314          103                  2  2.0   3.0  8.21         0

In [77]:
y1.head()

0    0.92
1    0.76
2    0.72
3    0.80
4    0.65
Name: Chance of Admit , dtype: float64

In [78]:
X_train1,X_test1,y_train1,y_test1 = train_test_split(X1,y1,test_size=0.25,random_state=10)

In [79]:
print(X_train1.shape,y_train1.shape)

(375, 7) (375,)


In [80]:
print(X_test.shape,1,y_test1.shape )

(528, 11) 1 (125,)


## preprocessing 

In [81]:
X_train1 = scaler.fit_transform(X_train1)

In [82]:
X_test1 = scaler.transform(X_test1)

## Model building

In [83]:
from sklearn.svm import SVR

In [84]:
svr = SVR()

In [85]:
svr.fit(X_train1,y_train1)

SVR()

In [86]:
svr_predict = svr.predict(X_test1)
svr_predict

array([0.86448478, 0.86417389, 0.64993814, 0.85127578, 0.70546036,
       0.7574019 , 0.64562856, 0.8374946 , 0.60540491, 0.7499413 ,
       0.87245167, 0.80905978, 0.8501926 , 0.67828992, 0.79563367,
       0.73813638, 0.70599962, 0.74942901, 0.74397623, 0.62461368,
       0.74524207, 0.62023823, 0.59939887, 0.86498548, 0.47403454,
       0.86577212, 0.73739421, 0.5349166 , 0.66114659, 0.6681512 ,
       0.88063063, 0.75792351, 0.59757618, 0.659533  , 0.72195655,
       0.86222102, 0.81603033, 0.66700444, 0.66986721, 0.70308992,
       0.86541166, 0.59529725, 0.69816638, 0.87297663, 0.85464852,
       0.50589332, 0.56266899, 0.65426092, 0.77984391, 0.72964663,
       0.79144637, 0.68053493, 0.54289505, 0.60234504, 0.65093636,
       0.79311027, 0.83658814, 0.61545878, 0.68815676, 0.86796428,
       0.61411511, 0.82414663, 0.73731365, 0.50901921, 0.83202811,
       0.5044696 , 0.70643466, 0.71803499, 0.52797734, 0.69684074,
       0.89743609, 0.55063192, 0.57081914, 0.73056104, 0.69386

### Perfomance Metrics

In [87]:
from sklearn.metrics import r2_score

### R2 score

In [88]:
svr_r2_score = r2_score(y_test1,svr_predict)
svr_r2_score

0.7570051002718872

### Adjusted R2 Score

In [89]:
adjusted_r2_score=1-((1-svr_r2_score)*(len(y_test1)-1)/(len(y_test1)-X_test1.shape[1]-1))
adjusted_r2_score

0.7424669438778975